# therock-host-blas
[components.lib."third-party/host-blas/host-blas/stage"]
[components.dbg."third-party/host-blas/host-blas/stage"]
[components.dev."third-party/host-blas/host-blas/stage"]
[components.doc."third-party/host-blas/host-blas/stage"]

# therock-host-blas64
[components.lib."third-party/host-blas/host-blas64/stage"]
[components.dbg."third-party/host-blas/host-blas64/stage"]
[components.dev."third-party/host-blas/host-blas64/stage"]
[components.doc."third-party/host-blas/host-blas64/stage"]
