# Copyright Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

name: Bump Submodule automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hrs at 12AM and 12PM
  push:
    branches:
      - main
    paths:
      - rocm-systems
      - rocm-libraries
jobs:
  bump-submodules:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout ROCm/TheRock
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'

      - name: Generate GitHub App token rocm-systems
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: systems-token
        with:
          app-id: ${{ secrets.ROCM_SYSTEMS_APP_ID }}
          private-key: ${{ secrets.ROCM_SYSTEMS_APP_PRIVATE_KEY }}
          owner: "ROCm"
          repositories: "rocm-systems,TheRock"

      - name: Generate GitHub App token rocm-libraries
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: librarian-token
        with:
          app-id: ${{ secrets.ROCM_LIBRARIES_APP_ID }}
          private-key: ${{ secrets.ROCM_LIBRARIES_APP_PRIVATE_KEY }}
          owner: "ROCm"
          repositories: "rocm-libraries,TheRock"

      - name: Install prerequisites
        run: |
          pip install requests

      - name: Run scheduled bump automation
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          python3 build_tools/github_actions/bump_automation.py \
            --event_type "schedule" \
            --systems_token "${{ steps.systems-token.outputs.token }}" \
            --libraries_token "${{ steps.librarian-token.outputs.token }}"

      - name: Run push automation
        if: github.event_name == 'push'
        run: |
          python3 build_tools/github_actions/bump_automation.py \
            --event_type "push" \
            --before "${{ github.event.before }}" \
            --after "${{ github.sha }}" \
            --systems_token "${{ steps.systems-token.outputs.token }}" \
            --libraries_token "${{ steps.librarian-token.outputs.token }}"
